# https://taskfile.dev

version: "3"

vars:
  PROJECT: walldo
  PROJECT_PKG: Walldo
  ENTRY: Walldo.py

tasks:
  default:
    cmds:
      - mamba run -n {{.PROJECT}} python {{.ENTRY}}
    silent: true

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true
  
  version:
    cmds:
      - mamba run -n {{.PROJECT}} python setup.py -v version

  build:
    desc: build app
    cmds:
      - mamba run -n {{.PROJECT}} python -m nuitka {{.ENTRY}}

  install:
    cmds:
      - killall {{.PROJECT_PKG}} || true
      - rm -rf /Applications/{{.PROJECT_PKG}}.app || true
      - mv Applications/{{.PROJECT_PKG}}.app /Applications
  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMG"
      - rm -f {{.PROJECT}}-arm64.dmg
      - ./node_modules/.bin/appdmg {{.PROJECT}}.json {{.PROJECT}}.dmg

  publish:
    desc: publish dmg file as package
    cmds:
      - echo "publishing app to github"
      - mamba run -n {{.PROJECT}} python -m deploy {{.CLI_ARGS}}

  deploy:
    cmds:
      - task: version
      - task: push
      - task: build
      - task: install

  release:
    desc: archive, dmg and upload package
    cmds:
      - task: version
      - task: push
      - task: build
      - task: dmg
      - task: publish
      - task: install
