# https://taskfile.dev

version: '3'

vars:
  PROJECT: walldo

tasks:
  default:
    cmds:
      - mamba run --live-stream -n {{.PROJECT}} python app.py
    silent: true


  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  build:
    cmds:
      - rm -rf build 
      - rm -rf dist
      - rm -rf .eggs
      - mamba run --live-stream -n {{.PROJECT}} python setup.py py2app

  install:
    cmds:
      - killall {{.Project}} || true
      - rm -rf /Applications/{{.PROJECT}}.app
      - mv dist/{{.PROJECT}}.app /Applications


  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml


  deploy:
    cmds:
      - task: push
      - task: build
      - task: install

